name: inr4ct
channels:
  - aahendriksen
  - pytorch
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - astra-toolbox=2.1.2
  - cudatoolkit=11.3.1
  - imageio=2.26.0
  - matplotlib=3.7.1
  - numpy=1.23.5
  - python=3.10.10
  - pytorch=1.11.0
  - scikit-image=0.19.2
  - scipy=1.10.0
  - tifffile=2021.4.8
  - tomopy=1.11.0
  - tomosipo=0.6.0
  - tqdm=4.65.0
